<?php

use Illuminate\Database\Seeder;

class WaivertextTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

    	DB::table('waivertext')->insert([
    		'year' => '2016',
    		'title' => 'LIABILITY RELEASE AND WAIVER AGREEMENT',
    		'version' => '01-JAN-2016',
    		'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus doloremque eos tempore accusantium reprehenderit sequi cum voluptate quidem suscipit similique quisquam laboriosam repudiandae eum voluptates tenetur voluptas unde consectetur repellat, quasi quaerat deleniti mollitia. Nostrum soluta fugit necessitatibus eius sunt consequuntur quas. Provident dignissimos maiores placeat doloremque repellat modi pariatur dolor ratione eum, architecto laudantium labore sapiente incidunt illo eius fugiat doloribus quae aliquam id veniam neque mollitia! Quos rem quam ipsam reprehenderit ullam nam autem eligendi recusandae provident inventore? Et quas obcaecati earum vel aliquam neque ut quidem aliquid. Asperiores porro incidunt, delectus facilis magnam dolor nobis perferendis, quas labore inventore a. Voluptatibus eligendi, voluptate, necessitatibus quisquam excepturi saepe quae et ab, consequatur natus molestias harum officiis incidunt dolor tempore? Voluptate tempore cumque suscipit quo aut eveniet sequi accusamus vel esse, exercitationem quia ipsum, impedit, debitis doloribus nulla! Repudiandae accusamus harum possimus culpa autem aliquid eveniet ex placeat eum!</p>
            <p>Sapiente corrupti laboriosam, recusandae sequi dolorem obcaecati architecto, corporis omnis aspernatur doloremque molestias suscipit culpa dignissimos cum rem quis eligendi nobis, soluta possimus ipsum et, dolore aliquam sunt quibusdam! Porro maiores, ex nam consequatur, fuga rerum ipsum magnam! Autem similique omnis accusantium minima labore, eligendi maxime, quibusdam fugit sunt culpa suscipit quod praesentium doloribus, rerum eveniet. Officiis expedita culpa laborum neque sit sed sint unde odio impedit architecto ullam consectetur vel esse iure nam ab voluptas enim recusandae, laudantium sequi quod? Dolor, labore, maiores. Porro quis voluptates quae beatae, nesciunt explicabo tempore, magnam earum illo laboriosam dolor quisquam expedita commodi omnis iure aliquam. Ad inventore sit consectetur magni corporis, excepturi fuga placeat recusandae impedit itaque iste sequi enim consequuntur ab cupiditate, neque eaque. Ipsam iusto beatae soluta obcaecati nostrum porro possimus blanditiis in aspernatur alias, ea earum eius laboriosam neque delectus quisquam non ipsum nam dignissimos, dolores sit autem dolore.</p>
            <p>Veritatis, voluptate, magnam. Vero incidunt eveniet aspernatur, consequatur optio! Quidem quisquam, quo ducimus a nobis molestias repudiandae! Enim facilis cumque, quia doloribus, a in consequatur repellat eligendi ea, quam quasi aperiam sit nihil optio id magni saepe nemo dignissimos aspernatur fugiat, debitis atque nisi. Asperiores eius dignissimos, veniam sed itaque harum nihil dolore soluta in porro amet est totam neque rerum libero reiciendis accusamus saepe quod, maxime quae voluptate error ut facilis! Quod asperiores, reprehenderit earum natus, repellat rerum obcaecati ad, architecto ex cum esse dolorum labore quam. Consectetur rem nobis facilis, atque obcaecati nemo perspiciatis quia, maiores hic nostrum animi ipsam dolores illo placeat est omnis ab, sint. Voluptatem sapiente, quibusdam eaque accusamus, dicta qui dolore. Vel consequatur, ab maxime, veniam corporis necessitatibus omnis, sint consequuntur repellat molestias totam odio ducimus cumque molestiae debitis dicta corrupti perferendis officia maiores laboriosam ex quae non qui! Dolores quidem consequuntur atque aperiam.</p>
            <p>Quibusdam illum nostrum dicta numquam temporibus quod vitae inventore, necessitatibus, vel consequatur facilis natus voluptatibus dolorum hic, dolores neque. Eveniet voluptas odio quae nulla iusto, harum reiciendis maiores delectus itaque, minima illo magni maxime! Optio libero impedit natus quisquam dolore reiciendis, autem aliquid eaque blanditiis ullam, sit aut quibusdam unde eligendi quaerat quidem soluta magnam. Repudiandae tempore laboriosam dignissimos quasi amet voluptas culpa. Temporibus natus, culpa dicta placeat doloremque nulla voluptatum iusto. Labore dolore optio, natus saepe quae, accusamus nostrum libero, neque, iste dignissimos odit nobis suscipit sunt placeat alias rem minus ea excepturi enim. Modi eligendi magnam quaerat provident iure nihil quod eveniet nam obcaecati animi expedita inventore illum nobis, voluptate fuga optio, ex recusandae quos. Quae molestiae quas delectus quidem perspiciatis et doloremque accusantium, laborum nam, recusandae quo repellat adipisci, quam culpa voluptas in explicabo ipsum. Enim ad, voluptas vitae, beatae magni ea eveniet corporis asperiores ipsum repudiandae!</p>
            <p>Delectus reprehenderit blanditiis accusantium hic dicta sed et ipsum molestias explicabo. Quos corporis cum, minima facilis! Consequatur, a eum assumenda, reiciendis impedit culpa totam veniam obcaecati, hic veritatis repudiandae animi aut. Cupiditate qui vero consectetur dolore error, rem quas, hic in, molestias at iusto omnis eligendi iste aspernatur incidunt cumque atque. Labore inventore nihil omnis ex ipsa eveniet sunt est aut, distinctio, possimus, nam eos quisquam temporibus porro tempore amet. Culpa incidunt hic illo? Eligendi, totam quis aspernatur rem inventore itaque consequatur, numquam beatae distinctio dolor maiores expedita nam, quae nisi blanditiis ipsum. Est voluptatibus provident velit, quisquam, consequuntur molestiae quo deleniti placeat, sunt expedita nobis culpa dicta? Quidem saepe incidunt, odio cupiditate illo, soluta facere dolores libero repellat vel quia possimus architecto iste? Amet velit temporibus explicabo voluptates ipsam asperiores porro expedita accusantium ratione nulla quisquam voluptas eius fuga sequi neque, aliquid illo facilis, dolorum vitae, impedit voluptatum consectetur!</p>',
    		'active_flag' => '1',
    		'active_date' => '2017-01-01'
    	]);

    	DB::table('waivertext')->insert([
    		'year' => '2017',
    		'title' => 'LIABILITY RELEASE AND WAIVER AGREEMENT',
    		'version' => '01-JAN-2017',
    		'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque tenetur porro doloremque et debitis consectetur tempore voluptas numquam maiores, cupiditate temporibus enim nisi, sed officiis tempora deleniti veniam quod in quos ipsum velit eligendi perspiciatis doloribus reiciendis. Omnis reiciendis quasi vero culpa debitis necessitatibus, inventore aliquid consequatur id quod vel error sequi itaque iusto vitae, quia, cupiditate facere porro dolores alias esse! Alias unde quis, dicta molestiae iusto labore aliquid iste in earum amet officiis eum, nobis accusamus consequatur itaque aspernatur cum dignissimos quidem vel quae. Accusamus quis ratione, atque officia laudantium velit adipisci ipsa odit quod qui culpa dolor id perferendis non nulla nostrum iste distinctio voluptate blanditiis, beatae. Ipsa nihil maiores, excepturi quibusdam delectus cumque pariatur vel ea aliquid quam, minus aliquam, similique facilis quasi placeat officiis inventore cupiditate nam magnam necessitatibus non hic laborum neque. Mollitia expedita id ea voluptatibus fugit magni, tempora! Quia dicta distinctio corrupti aliquam error velit incidunt dolor, possimus officia, illo eum! Tempore fugiat itaque, sit eaque nisi. Tenetur perspiciatis et asperiores, natus minima, labore quisquam. Aspernatur dolor earum labore sit! Cupiditate, pariatur. Modi fuga, molestias natus optio tempore quidem sunt perspiciatis error voluptatibus temporibus, quia laudantium fugiat odio officiis soluta voluptas delectus.</p>
            <p>Eum, est, aliquam. Dolores molestiae eveniet sequi, numquam nisi voluptatum, ut officia et nam esse! Molestiae distinctio, tenetur error, assumenda, dolorum quidem deleniti delectus excepturi similique praesentium consequatur eligendi inventore perspiciatis, aliquam. Perspiciatis excepturi, neque tempore distinctio et, quo quos consequuntur tenetur facilis laborum deleniti itaque perferendis, sit mollitia obcaecati non earum sint numquam facere recusandae provident iste? At, laudantium dolorum quo, iusto quia quod minima tempora voluptas eos tenetur possimus tempore laboriosam dolores quibusdam, cum, quasi placeat dicta similique perspiciatis vero autem ullam. Commodi, corrupti fugiat dolorum similique et architecto repudiandae, eligendi repellat sapiente nulla ducimus, aperiam velit dolores natus atque quam asperiores suscipit quae animi ullam voluptates provident accusamus. Earum voluptas maxime vitae eius optio quasi, aliquam, impedit nihil dicta blanditiis quidem iste unde est neque. Accusantium sunt nihil voluptatibus sapiente deleniti accusamus nobis natus est! Magni placeat, delectus. Aliquam culpa sint fugit enim iure repellat laboriosam. Ipsam fugiat recusandae veritatis facere, at, aspernatur quibusdam asperiores excepturi! Quod eum, error officiis? Quis nobis soluta, consequatur enim optio cumque repudiandae, perspiciatis laborum delectus! Vitae minima earum cupiditate, iste facere ex labore, ut doloremque dolorem quasi modi adipisci amet esse dolore repellendus, ducimus tempora! Dolorem doloribus, at? Modi, commodi, facilis!</p>
            <p>Consequatur tempore in rem atque aliquid eligendi ad debitis velit. Dolorem deleniti eligendi asperiores ratione libero sed nemo voluptate cum dicta, ipsa, minus iure cumque nulla. Ullam commodi cupiditate animi, nostrum consequatur nisi libero quia, eius incidunt possimus labore tempora rerum, iste nam sapiente dolores debitis! Voluptates dignissimos cumque praesentium nobis, repudiandae laborum suscipit, nam facere reiciendis error, amet, ipsam consequuntur a. Incidunt eveniet rerum magni totam, nisi ab accusamus nulla repellendus praesentium voluptatem, dolorum fuga fugiat qui aperiam tempore eligendi ratione! Delectus tempore et, provident laudantium beatae, eius atque voluptas impedit inventore molestiae fuga itaque? Doloremque ab debitis quibusdam pariatur blanditiis. Eveniet maiores ex hic accusamus voluptates, reprehenderit vitae officia ea quis voluptatum id eius dolor sed rem laboriosam odio, dolorum unde sunt possimus nemo dolores iure deserunt placeat, ratione sapiente. Debitis, vitae dolores repellendus. Tempore quas magni fugiat iure. Sit, consequuntur. Ab hic aperiam ullam tempore distinctio minima eius fugiat consequatur repudiandae, quia veritatis iure facilis repellat, sunt nemo, veniam, incidunt praesentium eveniet rerum adipisci ducimus doloribus tempora. Itaque nobis debitis, nihil dignissimos ipsum delectus ullam officiis libero, nulla dicta molestiae nemo, odio totam commodi cupiditate accusantium repellat perspiciatis eligendi cum repellendus illum facilis? Incidunt pariatur, optio doloremque.</p>
            <p>Debitis error adipisci veniam aut. Soluta tenetur atque eligendi dolore ab deleniti eveniet culpa earum. Fuga temporibus natus ipsam, quam nisi maxime nulla voluptatibus iusto, nihil dignissimos enim sint, a incidunt dolore aspernatur recusandae laudantium reiciendis. Adipisci commodi distinctio saepe nostrum soluta, totam eveniet sit beatae voluptates officia placeat ea, libero minus recusandae fugiat, temporibus enim eius nihil debitis. Atque nihil quod iure quae, eius, vitae voluptatum laboriosam, dicta expedita et nostrum ducimus! Eos sapiente adipisci doloribus numquam, modi aperiam provident dolores aspernatur est! Dolorum a, at blanditiis quo nesciunt possimus, inventore. Deleniti quibusdam dolore debitis deserunt, architecto reprehenderit obcaecati natus ut adipisci ipsa temporibus ea! Aut repudiandae tenetur quae quis ipsum, pariatur labore doloremque, rerum laborum sint placeat voluptatem commodi earum explicabo aliquam et atque quidem. Recusandae dignissimos aut, perferendis aliquid quisquam odit quae eligendi dolore, veniam nostrum eveniet rerum ad iure, ut adipisci non nulla obcaecati. Nobis, consequuntur officia in aspernatur beatae deleniti sequi eaque tenetur id, dolor voluptates voluptate qui suscipit, voluptatem cum assumenda, labore possimus dolore incidunt aliquid mollitia! Non, fuga, eaque! Cumque iure reiciendis perspiciatis quas voluptatum saepe, non odio corporis expedita exercitationem quibusdam repellendus pariatur ipsum, voluptatibus sunt sapiente, aliquid quo. Accusamus, adipisci, aliquid.</p>
            <p>Eum nemo consectetur aliquid, animi accusantium omnis facilis dolorum tenetur odio vitae amet error ut cumque dignissimos, suscipit, neque cum nesciunt rerum, at odit incidunt dolores. Neque architecto, non maiores consequatur eveniet fuga incidunt aliquam necessitatibus delectus, veniam dolorum temporibus, totam qui. Explicabo, velit officiis optio ducimus possimus quia, eveniet debitis ex maxime, nesciunt nihil unde voluptates! Corporis unde sequi ducimus, ea sit nihil laborum. Dolore, illo, tempora. Quasi voluptatem, reiciendis deserunt fuga minus ratione iste, maiores odio numquam quibusdam officiis, sapiente quidem possimus libero. Recusandae porro nisi nihil neque ipsa praesentium eum delectus modi eos expedita, id ex soluta, ipsam dolor vel quisquam sit quaerat corporis. Deserunt enim, laboriosam eos maiores ipsa rem aliquam cumque similique cum delectus perspiciatis doloribus placeat mollitia. Accusantium voluptatem totam ratione ipsum inventore omnis, hic nobis nam, ea facere natus amet voluptatum perferendis recusandae unde optio quis ab dolor, consectetur, eaque quisquam molestiae veritatis incidunt quae? Dolorem iste excepturi commodi quia eligendi rem molestias officia inventore voluptatibus, quasi. Architecto ex ullam rerum voluptas deserunt omnis, corporis officiis laboriosam quos, itaque quo, modi non. Accusantium sint minima, culpa vel incidunt architecto molestiae, asperiores distinctio iste fuga officia recusandae repellendus perferendis tenetur sapiente ipsa minus? Vero.</p>',
    		'active_flag' => '1',
    		'active_date' => '2018-01-01'
    	]);

    	DB::table('waivertext')->insert([
    		'year' => '2018',
    		'title' => 'LIABILITY RELEASE AND WAIVER AGREEMENT',
    		'version' => '15-JAN-2018',
    		'body' => str_random(100),
    		'active_flag' => '0',
    		'active_date' => '2018-01-15'
    	]);
    }
}
